name: IntegrationTest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make develop

    - name: Test with pytest
      run: |
        pytest tests/integrations

    - name: Notify test results to slack
      uses: 8398a7/action-slack@v2.6.0
      with:
        status: ${{job.status}}
        author_name: LFT2-Integrations
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # require

    - name: View files
      run: ls -al

    - name: Zip eventlogs
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip integration_results.zip test_*

    - name: Post results to slack
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: test.zip
        channel: group-consensus-noti
