name: IntegrationTest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: view files
      run: ls -al

    - name: Zip eventlogs
      run: zip lft.zip lf*

    - name: Post results to slack
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: lft.zip
        channel: group-consensus-noti
