name: IntegrationTest

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make develop

    - name: Test with pytest
      run: |
        pytest tests/integrations

    - name: Notify test results to slack
      uses: 8398a7/action-slack@v2.6.0
      with:
        status: ${{job.status}}
        author_name: LFT2-Integrations ${{ GITHUB_REF##*/ }}
        fields: repo,ref
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Zip eventlogs
      run: zip -r integration_result.zip test_*
      if: failure()

    - name: Post results to slack
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_TOKEN }}
        path: integration_result.zip
        channel: group-consensus-noti
      if: failure()
